# Generated by Django 2.0.6 on 2018-06-22 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_app', '0004_auto_20180622_1630'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quote',
            name='likes',
        ),
        migrations.AddField(
            model_name='quote',
            name='likes',
            field=models.ManyToManyField(related_name='likes', to='users_app.User'),
        ),
    ]
